import { DollarSign, Heart, Calculator, Settings, Ruler, Sigma } from "lucide-react"

export const categories = [
  {
    title: "Financial Calculators",
    icon: DollarSign,
    color: "bg-green-100 text-green-700",
    href: "/financial",
    calculators: [
      { name: "Mortgage Calculator", href: "/financial/mortgage-calculator" },
      { name: "Loan Calculator", href: "/financial/loan-calculator" },
      { name: "Auto Loan Calculator", href: "/financial/auto-loan-calculator" },
      { name: "Interest Calculator", href: "/financial/interest-calculator" },
      { name: "Payment Calculator", href: "/financial/payment-calculator" },
      { name: "Retirement Calculator", href: "/financial/retirement-calculator" },
      { name: "Amortization Calculator", href: "/financial/amortization-calculator" },
      { name: "Investment Calculator", href: "/financial/investment-calculator" },
      { name: "Inflation Calculator", href: "/financial/inflation-calculator" },
      { name: "Finance Calculator", href: "/financial/finance-calculator" },
      { name: "Income Tax Calculator", href: "/financial/income-tax-calculator" },
      { name: "Compound Interest Calculator", href: "/financial/compound-interest-calculator" },
      { name: "Salary Calculator", href: "/financial/salary-calculator" },
      { name: "Interest Rate Calculator", href: "/financial/interest-rate-calculator" },
      { name: "Sales Tax Calculator", href: "/financial/sales-tax-calculator" },
      { name: "GDP Calculator", href: "/financial/gdp-calculator" },
    ],
  },
  {
    title: "Fitness & Health Calculators",
    icon: Heart,
    color: "bg-red-100 text-red-700",
    href: "/health",
    calculators: [
      { name: "BMI Calculator", href: "/health/bmi-calculator" },
      { name: "Calorie Calculator", href: "/health/calorie-calculator" },
      { name: "Body Fat Calculator", href: "/health/body-fat-calculator" },
      { name: "BMR Calculator", href: "/health/bmr-calculator" },
      { name: "Ideal Weight Calculator", href: "/health/ideal-weight-calculator" },
      { name: "Pace Calculator", href: "/health/pace-calculator" },
      { name: "Pregnancy Calculator", href: "/health/pregnancy-calculator" },
      { name: "Pregnancy Conception Calculator", href: "/health/pregnancy-conception-calculator" },
      { name: "Due Date Calculator", href: "/health/due-date-calculator" },
    ],
  },
  {
    title: "Math Calculators",
    icon: Calculator,
    color: "bg-blue-100 text-blue-700",
    href: "/math",
    calculators: [
      { name: "Scientific Calculator", href: "/math/scientific-calculator" },
      { name: "Fraction Calculator", href: "/math/fraction-calculator" },
      { name: "Percentage Calculator", href: "/math/percentage-calculator" },
      { name: "Random Number Generator", href: "/math/random-number-generator" },
      { name: "Triangle Calculator", href: "/math/triangle-calculator" },
      { name: "Standard Deviation Calculator", href: "/math/standard-deviation-calculator" },
    ],
  },
  {
    title: "Data Science Calculators",
    icon: Sigma,
    color: "bg-indigo-100 text-indigo-700",
    href: "/data-science",
    calculators: [
      { name: "Mean (Average)", href: "/data-science/mean-average-calculator" },
      { name: "Median (Middle Value)", href: "/data-science/median-middle-value-calculator" },
      { name: "Mode (Most Frequent Value)", href: "/data-science/mode-most-frequent-value-calculator" },
      { name: "Variance (Measure of Spread)", href: "/data-science/variance-measure-of-spread-calculator" },
      { name: "Standard Deviation (Spread Around Mean)", href: "/data-science/standard-deviation-spread-around-mean-calculator" },
      { name: "Covariance (Joint Variability)", href: "/data-science/covariance-joint-variability-calculator" },
      { name: "Pearson Correlation Coefficient", href: "/data-science/pearson-correlation-coefficient-calculator" },
      { name: "Quantiles / Percentiles", href: "/data-science/quantiles-percentiles-calculator" },
      { name: "Z-Score (Standard Score)", href: "/data-science/z-score-standard-score-calculator" },
    ],
  },
  {
    title: "Linear Algebra Calculators",
    icon: Sigma,
    color: "bg-yellow-100 text-yellow-700",
    href: "/linear-algebra",
    calculators: [
      { name: "Vector Addition", href: "/linear-algebra/vector-addition-calculator" },
      { name: "Vector Subtraction", href: "/linear-algebra/vector-subtraction-calculator" },
      { name: "Scalar Vector Multiplication", href: "/linear-algebra/scalar-vector-multiplication-calculator" },
      { name: "Dot Product", href: "/linear-algebra/dot-product-calculator" },
      { name: "Cross Product", href: "/linear-algebra/cross-product-calculator" },
      { name: "Matrix Addition", href: "/linear-algebra/matrix-addition-calculator" },
      { name: "Matrix Subtraction", href: "/linear-algebra/matrix-subtraction-calculator" },
      { name: "Scalar Matrix Multiplication", href: "/linear-algebra/scalar-matrix-multiplication-calculator" },
      { name: "Matrix Multiplication", href: "/linear-algebra/matrix-multiplication-calculator" },
      { name: "Matrix Transpose", href: "/linear-algebra/matrix-transpose-calculator" },
      { name: "Matrix Determinant", href: "/linear-algebra/matrix-determinant-calculator" },
      { name: "Matrix Trace", href: "/linear-algebra/matrix-trace-calculator" },
    ],
  },
  {
    title: "Optimization-related calculations",
    icon: Settings,
    color: "bg-teal-100 text-teal-700",
    href: "/optimization",
    calculators: [
      { name: "Gradient (vector of partial derivatives)", href: "/optimization/gradient-vector-of-partial-derivatives-calculator" },
      { name: "Partial Derivatives", href: "/optimization/partial-derivatives-calculator" },
      { name: "Jacobian Matrix", href: "/optimization/jacobian-matrix-calculator" },
      { name: "Hessian Matrix", href: "/optimization/hessian-matrix-calculator" },
      { name: "Chain Rule", href: "/optimization/chain-rule-calculator" },
      { name: "Lagrange Multiplier", href: "/optimization/lagrange-multiplier-calculator" },
      { name: "Backpropagation", href: "/optimization/backpropagation-calculator" },
      { name: "Gradient Descent Update", href: "/optimization/gradient-descent-update-calculator" },
    ],
  },
  {
    title: "Investment Calculators",
    icon: DollarSign,
    color: "bg-amber-100 text-amber-700",
    href: "/investment",
    calculators: [
      { name: "Return on Investment (ROI)", href: "/investment/return-on-investment-roi-calculator" },
      { name: "Compound Annual Growth Rate (CAGR)", href: "/investment/compound-annual-growth-rate-cagr-calculator" },
      { name: "Annualized Return", href: "/investment/annualized-return-calculator" },
      { name: "Absolute Return", href: "/investment/absolute-return-calculator" },
      { name: "Total Return", href: "/investment/total-return-calculator" },
      { name: "Holding Period Return (HPR)", href: "/investment/holding-period-return-hpr-calculator" },
      { name: "Price-to-Book (P/B) Ratio", href: "/investment/price-to-book-pb-ratio-calculator" },
      { name: "Price-to-Sales (P/S) Ratio", href: "/investment/price-to-sales-ps-ratio-calculator" },
      { name: "Enterprise Value (EV)", href: "/investment/enterprise-value-ev-calculator" },
      { name: "EV/EBITDA", href: "/investment/evebitda-calculator" },
      { name: "PEG Ratio", href: "/investment/peg-ratio-calculator" },
      { name: "Value at Risk (VaR)", href: "/investment/value-at-risk-var-calculator" },
      { name: "Maximum Drawdown", href: "/investment/maximum-drawdown-calculator" },
      { name: "Capital Asset Pricing Model (CAPM)", href: "/investment/capital-asset-pricing-model-capm-calculator" },
      { name: "Margin of Safety", href: "/investment/margin-of-safety-calculator" },
    ],
  },
  {
    title: "Various Measurements/Units",
    icon: Ruler,
    color: "bg-orange-100 text-orange-700",
    href: "/measurements",
    calculators: [
      { name: "Height Calculator", href: "/measurements/height-calculator" },
      { name: "Weight Calculator", href: "/measurements/weight-calculator" },
      { name: "Mass Calculator", href: "/measurements/mass-calculator" },
      { name: "Density Calculator", href: "/measurements/density-calculator" },
      { name: "Speed Calculator", href: "/measurements/speed-calculator" },
      { name: "Conversion Calculator", href: "/measurements/conversion-calculator" },
      { name: "Molarity Calculator", href: "/measurements/molarity-calculator" },
    ],
  },
  {
    title: "Other Calculators",
    icon: Settings,
    color: "bg-purple-100 text-purple-700",
    href: "/other",
    calculators: [
      { name: "Age Calculator", href: "/other/age-calculator" },
      { name: "Date Calculator", href: "/other/date-calculator" },
      { name: "Time Calculator", href: "/other/time-calculator" },
      { name: "Hours Calculator", href: "/other/hours-calculator" },
      { name: "GPA Calculator", href: "/other/gpa-calculator" },
      { name: "Grade Calculator", href: "/other/grade-calculator" },
      { name: "Concrete Calculator", href: "/other/concrete-calculator" },
      { name: "Subnet Calculator", href: "/other/subnet-calculator" },
      { name: "Password Generator", href: "/other/password-generator" },
      { name: "Roman Numeral Converter", href: "/other/roman-numeral-converter" },
      { name: "Molecular Weight Calculator", href: "/other/molecular-weight-calculator" },
    ],
  },
] 